algorithm:
  max_local_epochs: 1
  pattern: constant
  total_silos: 5
  type: fedavg
clients:
  do_test: false
  per_round: 4
  simulation: false
  total_clients: 10
data:
  concentration: 0.5
  data_path: ./data
  datasource: FashionMNIST
  partition_size: 1000
  random_seed: 10
  sampler: orthogonal
results:
  plot: round&accuracy, round&training_time
  types: accuracy, training_time, round_time, loss
server:
  address: 127.0.0.1
  port: 8000
trainer:
  batch_size: 50
  epochs: 1
  learning_rate: 0.01
  model_name: mlp
  momentum: 0
  mu: 0.1
  optimizer: FedProx
  parallelized: false
  rounds: 100
  target_accuracy: 0.98
  type: basic
  weight_decay: 0.0
