algorithm:
  type: fedbn
clients:
  do_test: false
  per_round: 4
  simulation: false
  total_clients: 20
  type: simple
data:
  data_path: ../momentum_adp/data
  datasource: MNIST
  partition_size: 160
  random_seed: 9
  sampler: noniid
results:
  plot: round&accuracy, round&training_time
  types: accuracy, training_time, round_time
server:
  address: 127.0.0.1
  port: 8001
trainer:
  batch_size: 16
  epochs: 1
  learning_rate: 0.001
  model_name: mlp
  momentum: 0.9
  optimizer: SGD
  parallelized: false
  rounds: 30
  target_accuracy: 0.98
  type: basic
  weight_decay: 0.0
