algorithm:
  total_silos: 5
  type: fedavg
clients:
  do_test: false
  per_round: 4
  simulation: false
  total_clients: 10
  type: simple
data:
  data_path: ../momentum_adp/data
  datasource: IMDB
  institution_class_ids: 0,1;2,3;4,5;6,7;8,9
  label_distribution: iid
  partition_size: 600
  random_seed: 0
  sampler: iid
results:
  plot: round&accuracy, round&training_time
  types: accuracy, training_time, round_time
server:
  address: 127.0.0.1
  port: 8019
trainer:
  batch_size: 50
  epochs: 1
  learning_rate: 1
  model_name: rnn
  momentum: 0
  mu: 0.1
  optimizer: FedProx
  parallelized: false
  rounds: 50
  target_accuracy: 0.98
  type: basic
  weight_decay: 0.0
