algorithm:
  total_silos: 5
  type: fedprox
clients:
  do_test: false
  per_round: 2
  simulation: false
  total_clients: 50
data:
  data_path: ../momentum_adp/data
  datasource: MNIST
  institution_class_ids: 0,1;2,3;4,5;6,7;8,9
  label_distribution: noniid
  partition_size: 600
  random_seed: 9
  sampler: noniid
results:
  plot: round&accuracy, round&training_time
  types: accuracy, training_time, round_time
server:
  address: 127.0.0.1
  port: 8003
trainer:
  batch_size: 50
  epochs: 1
  learning_rate: 0.01
  model_name: lenet
  momentum: 0
  optimizer: FedProx
  mu: 0.1
  parallelized: false
  rounds: 50
  target_accuracy: 0.98
  weight_decay: 0.0
