clients:
    # The total number of clients
    total_clients: 10

    # The number of clients selected in each round
    per_round: 2

    # Should the clients compute test accuracy locally?
    do_test: false

server:
    address: 127.0.0.1
    port: 8099

data:
    # The training and testing dataset
    datasource: IMDB

    # Where the dataset is located
    data_path: ../momentum_adp/data

    # Number of samples in each partition
    partition_size: 600

    # IID or non-IID?
    sampler: iid

trainer:
    # The maximum number of training rounds
    rounds: 50

    # Whether the training should use multiple GPUs if available
    parallelized: false

    # The target accuracy
    target_accuracy: 0.98

    # Number of epoches for local training in each communication round
    epochs: 1
    batch_size: 32
    optimizer: FedSarah
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 0.0

    # The machine learning model
    model_name: rnn

algorithm:
    # Aggregation algorithm
    type: fedavg
